### PR TITLE
Escodex Integration

### PR DESCRIPTION
**Pull request by estherleongym**
- Implemented Pairs, Tickers, and updated README for Escodex
- Related to issue #631 
- [ X ] I have added Specs
- [ X ] (If implementing Market Ticker) I have verified that the `volume` refers to BASE
- [ X ] (If implementing Market Ticker) I have verified that the `base` and `target` is assigned correctly

### CODE REVIEW

**Comment by tmlee** [comment]
@estherleongym is the API working for you? https://coinapi.escodex.com:9090/ticker

**Comment by estherleongym** [comment]
@tmlee it's not working for me now, let me see if I can listen for another endpoint

**Comment by tmlee** [comment]
Got it, @estherleongym try clearer up the conflicting files, you might not need it here

**Comment by tmlee** [comment]
Conflict resolved in this branch/PR https://github.com/coingecko/cryptoexchange/pull/896

**Pull request closed without merging**
