### PR TITLE
change ticker volume to base volume(ready)

### PR DESCRIPTION
**Pull request by Swingcloud**

### CODE REVIEW

**Comment by tmlee** [comment]
For `coin_exchange`, the 2 volume attributes seem to return the same data
https://www.coinexchange.io/api/v1/getmarketsummaries which looks like a bug on their API

Since we are looking for base, shouldn't we opt for `Volume` instead of `BTCVolume`?

**Comment by Swingcloud** [comment]
Ok! so i just change `coin_exchange` volume to `Volume` instead of `BTCVolume`?

**Comment by tmlee** [comment]
@Swingcloud That won't be exactly correct too, since the `volume` is denominated in `BTC`.
I dont know if it is correct to divide the `BTC` with the `base` currency.
@dominicwong617 @yihangho thoughts?

**Comment by tmlee** [comment]
Same issue with https://github.com/coingecko/cryptoexchange/issues/58
However I do think the best solution is to divide its own price.

I've a few thoughts that I am not sure which is the best yet.

1. Dictate and divide the `target` volume with the price to get volume in `base` 
2. If `base` volume is not available, then do not assign to the volume. Create a new column like `volume_target`. Give the user the option to use that and decide if they want to divide it.

**Comment by Swingcloud** [comment]
I think divide is the better way to solve this, let me do it

**Comment by Swingcloud** [comment]
maybe option 2 is the better way to deal with this?

**Comment by tmlee** [comment]
@Swingcloud I think lets hotfix this and take care of the volume with the user by calculating it against the `last` price. I'll create a separate issue listing the exchange that contains this issue to revisit.

**Pull request merged**
