### PR TITLE
WE HOPE TO BE ADDED ON THE LIST OF EXCHANGE RANKINGS

### PR DESCRIPTION
**Pull request by katherinefang**
- What is the purpose of this Pull Request?
- What is the related issue for this Pull Request?
- [ ] I have added Specs
- [ ] (If implementing Market Ticker) I have verified that the `volume` attributes is correct
- [ ] (If implementing Market Ticker) I have verified that the `base` and `target` is correct

To whom it may concern:
  I hope it won't be very rude to write to you directly. First, I'm gonna introduce myself briefly. This is Katherine, international marketing manager of KK Exchange(www.kkex.com). Here I will explain why I write.
 [KKEX], a brand-new international blockchain asset exchange, is wholly owned by KKEX Technology Co., Ltd in the Republic of Seychelles. Currently, we have launched BCC/BTC, BT1/BTC, BT2/BTC, BTG/BTC trading pairs, the LENDING and more trading pairs are coming soon.
  And we hope that we can be one of your exchange rankings. If that could be possible, what we need to do or do you have time to talk about details?
  Your attention and answer will be fully appreciated.
Best regards.

### CODE REVIEW

**Comment by tmlee** [comment]
Hi @katherinefang ,

This library strives to include as much exchange as possible and your exchange is absolutely something we want to support.
https://www.coingecko.com uses this library backend and we can add it as soon as it is implemented.

I'll be moving this request into the Issues section for now. If there are engineering resources on our end we will be implementing it, otherwise someone from the community may pick this up, or engineers on your end can implement it here as well.

**Comment by katherinefang** [comment]
https://kkex.com/api_wiki/en/ 
Hello, is this what you need? If there is any problem, please feel free to contact me. Thanks.

**Comment by tmlee** [comment]
that should be helpful, thanks!

**Comment by katherinefang** [comment]
Hi, sorry to disturb. Any updates? Is it possible to add our exchange?

**Comment by tmlee** [comment]
@katherinefang If no one from the community work on it, it will hopefully be worked on soon by our own resources.

**Pull request closed without merging**
