### PR TITLE
[WIP] revert

### PR DESCRIPTION
**Pull request by JaredParsons**
- What is the purpose of this Pull Request?
- What is the related issue for this Pull Request?
- [x] I have added Specs
- [x] (If implementing Market Ticker) I have verified that the `volume` refers to BASE
- [x] (If implementing Market Ticker) I have verified that the `base` and `target` is assigned correctly

### CODE REVIEW

**Comment by tmlee** [comment]
@JaredParsons What is the PR addressing?

**Comment by JaredParsons** [comment]
I don't know what's going on what do I do

Get Outlook for Android

________________________________

**Comment by JaredParsons** [comment]
Look I Apologies what PR.
________________________________

**Comment by JaredParsons** [comment]
Could you give me a quick run through on this process also Im curious what did I do how did I end up this address why did I end up with this address and I would like answers.
  Why has bitcoin been advertising me crypto addresses handing my work out like candy
________________________________

**Pull request closed without merging**
