### PR TITLE
handling gzip response

### PR DESCRIPTION
**Pull request by Iworb**
For further work it should be implemented if server returns only gzipped data.

### CODE REVIEW

**Comment by Iworb** [comment]
Looks like there's a single site (Latoken) who sends header 'Content-Encoding' => 'gzip' withot actually gzipping content.

**Comment by tmlee** [comment]
@Iworb Will you be able to include a spec for Latoken to tackle this scenario?

**Comment by Iworb** [comment]
Well, it will be wrong if I include catching for `latoken` only. It depends on server response with wrong headers: content is not gzipped, but response header says it is. I don't know was there a temporary error or constant, could we re-run this spec?

**Comment by Iworb** [comment]
`rspec spec/echanges/latoken` works fine. Could it be some temporary server-side error?
Is there a way to re-run Travis check?
image

**Pull request closed without merging**
