### PR TITLE
✨ Implement Altmarkets Ticker and Order book

### LINKED ISSUE #907: Implement altmarkets
www.altmarkets.cc
https://altmarkets.cc/API

### PR DESCRIPTION
**Pull request by Swingcloud**
- What is the purpose of this Pull Request? as title 
- What is the related issue for this Pull Request (if this PR fixes issue, prepend with "Fixes" or "Closes")? closes #907
- [x] I have added Specs
- [x] (If implementing Market Ticker) I have verified that the `volume` refers to BASE
- [x] (If implementing Market Ticker) I have verified that the `base` and `target` is assigned correctly

ticker about `ADVP_BTC`
```ruby
{
 "MarketName": "BTC-ADVP",
 "High": "0.00000001",
 "Low": "0.00000001",
 "Volume": "179260.87700000",
 "Last": "0.00000001",
 "Bid": "0.00000000",
 "Ask": "0.00000003",
 "OpenBuyOrders": 0,
 "OpenSellOrders": 15,
 "coin_icon_src": "https%3A//i.imgur.com/H6LNq7Y.png",
 "coin_info": {
  "hold": 0.01,
  "page": "https://bitcointalk.org/index.php?topic=4563189.0",
  "active": true,
  "minconf": 3,
  "withdraw": "Enabled",
  "orders": "Enabled"
 }
}
```
use `volume` as base volume

and their trades endpoint is broken, so just leave it for now
https://altmarkets.cc/api/v1/public/getmarkethistory?market=BTC-LTC

### CODE REVIEW

**Comment by Swingcloud** [comment]
seems there's some issue about  `Coinchangex`, will check if there VCR files on Coinchangex or not

**Comment by jonn4y** [comment]
Hi @Swingcloud this API error has now been fixed: https://altmarkets.cc/api/v1/public/getmarkethistory?market=BTC-LTC

Thanks

**Comment by Swingcloud** [comment]
hello @jonn4y , I've updated! thanks!

**Comment by wongy91** [comment]
LGTM.

**Pull request merged**
